### ISSUE TITLE
Beacon not working

### ISSUE THREAD

**Issue by kshmr** [line/line-simple-beacon#1]
I've used my macOS Sierra on Apple's Computer with Bluetooth LE to run `node simplebeacon.js --hwid=<MY-HWID>` with valid HWID and valid bot (since my bot works fine before). The problem is when i get to close my LINE user client to my mac (running simple beacon) it's not trigger webhook to send something from my bot. is there setup I've skipped or anything else ?
Also, I've read you guys article from here : https://engineering.linecorp.com/ja/blog/detail/117 to get any detail, but there is still no hope for me.

**Comment by yohsuke** [comment]
You are in Berkeley?

Now "LINE Beacon" is opened only in Japan, Taiwan or Thailand.
Then only users in there regions can use LINE Simple Beacon.

**Comment by yohsuke** [comment]
I'll close this by current-spec-limitation. Please reopen if there is any difference in recognition.
