### ISSUE TITLE
Beacon Register URL changed.

### ISSUE THREAD

**Issue by taichunmin** [line/line-simple-beacon#14]
After a LINE@ account migrate to a LINE official account, the beacon register url also change to `https://manager.line.biz/beacon/register` . But a not migrated LINE@ account still need to register by old url `https://admin-official.line.me/beacon/register`. Should we update the register url in specification?

**Comment by yohsuke** [comment]
Thank you for pointing out.

As you said, we have to use 'manager.line.biz' with a new official account / migrated LINE @ account.

However, it is also necessary to use the old 'admin-official.line.me' URL until the update is completely finished, so we will add some notes about the above.

Please wait.

**Comment by yohsuke** [comment]
Updated.
