### ISSUE TITLE
About beacoun event...

### ISSUE THREAD

**Issue by michliu** [line/line-simple-beacon#3]
While I am testing Line Beacon, for Android user can receive the beacon event(like enter or leave), but it doesn’t work with iPhone user, can you please explain why, is there any solution for iPhone user to receive the event?

**Comment by yohsuke** [comment]
Please check the follows:

1. Bluetooth is ON?
2. Select "Use LINE Beacon"
	see LINE app -> Settings > Privacy
3. Already added your bot as friend ?

And also check the following location settings on iOS:

4. The value of "Location Service" is "ON" ?
	see Settings -> Privacy -> Location Services -> "Location Services (top most)"
5. The value of "LINE App Location Access" is "ALWAYS?"
	see Settings -> Privacy -> Location Services -> "LINE"

To use LINE Beacon, location information access is required.
