### ISSUE TITLE
Currently not working in MacOS Mojave

### ISSUE THREAD

**Issue by micksatana** [line/line-simple-beacon#9]
Hi,

Just to report an issue that it's currently not working in MacOS Mojave due to this issue.

https://github.com/noble/bleno/issues/404

**Comment by tokuhirom** [comment]
hm... so should we switch to the https://github.com/Timeular/noble-mac ?
@yohsuke

**Comment by yohsuke** [comment]
I found [bleno-mac](https://github.com/notjosh/bleno-mac) (this is better for our use than "noble-mac" because "line simple beacon" is a BLE peripheral)
However, this library seems to be under construction, and some methods we need seem to be not yet completely implemented 😢  .

**Comment by yohsuke** [comment]
It seems difficult to implement LINE Simple Beacon using `CoreBluetooth` API.
In the API, [the advertisable parameter types are strongly restricted by Apple](https://developer.apple.com/documentation/corebluetooth/cbperipheralmanager/1393252-startadvertising#parameters
).
That makes us inpossible to broadcast `ServiceData` that is used in our LINE Simple Beacon.

Also I have found some similar problems with us (these are for iOS, but the same on Mac I think):
- https://stackoverflow.com/questions/35175035
- https://github.com/koutalou/BeaconRegionManager/issues/4

`bleno` seems to have avoided this problem by using a technology different from `CoreBluetooth`.
We are currently looking for the workaround like it , 
It is very heartbreaking, but we can not support Mojave or later until we find it.
